# coding=utf-8
scifinames = [
   u"Dafydd ab Hugh",
   u"Alexander Abasheli",
   u"Edwin Abbott",
   u"Kōbō Abe",
   u"Robert Abernathy",
   u"Dan Abnett",
   u"Forrest J Ackerman",
   u"Douglas Adams",
   u"Robert Adams",
   u"Jerry Ahern",
   u"Humayun Ahmed",
   u"Jim Aikin",
   u"Alan Burt Akers",
   u"Brian Aldiss",
   u"David M. Alexander",
   u"Lloyd Alexander",
   u"Roger MacBride Allen",
   u"Hans Joachim Alpers",
   u"Steve Alten",
   u"Genrich Altov",
   u"Genrich Altshuller",
   u"Kingsley Amis",
   u"Paul Rafaelovich Amnuél",
   u"Kevin J. Anderson",
   u"Poul Anderson",
   u"Christopher Andrews",
   u"Patricia Anthony",
   u"Piers Anthony",
   u"Christopher Anvil",
   u"K. A. Applegate",
   u"E.L. Arch",
   u"Eleanor Arnason",
   u"Robert Arthur",
   u"Catherine Asaro",
   u"Neal Asher",
   u"Francis Leslie Ashton",
   u"Isaac Asimov",
   u"Janet Asimov",
   u"Nancy Asire",
   u"Robert Asprin",
   u"A. A. Attanasio",
   u"Margaret Atwood",
   u"Ayerdhal",
   u"Richard Bachman",
   u"Paolo Bacigalupi",
   u"Hilary Bailey",
   u"Kage Baker",
   u"Scott Baker",
   u"J. G. Ballard",
   u"Iain M. Banks",
   u"Raymond E. Banks",
   u"Marek Baraniecki",
   u"Miquel Barceló",
   u"René Barjavel",
   u"Arthur K. Barnes",
   u"John Barnes",
   u"Steven Barnes",
   u"William Barnwell",
   u"Donald Barr",
   u"João Barreiros",
   u"William Barton",
   u"T. J. Bass",
   u"Harry Bates",
   u"L. Frank Baum",
   u"John Baxter",
   u"Stephen Baxter",
   u"Georgy Baydukov",
   u"Barrington J. Bayley",
   u"Elizabeth Bear",
   u"Greg Bear",
   u"Jerome Beatty Jr",
   u"Charles Beaumont",
   u"Vladimir Beekman",
   u"Alexander Beliaev",
   u"Edward Bellamy",
   u"Andrei Belyanin",
   u"Don Bendell",
   u"Gregory Benford",
   u"J. D. Beresford",
   u"Fyodor Berezin",
   u"Cyrano de Bergerac",
   u"Jack Bertin",
   u"Alfred Bester",
   u"Bruce Bethke",
   u"Ambrose Bierce",
   u"Lloyd Biggle, Jr.",
   u"Eando Binder",
   u"John Birmingham",
   u"David Bischoff",
   u"Michael Bishop",
   u"Terry Bisson",
   u"Jerome Bixby",
   u"Malorie Blackman",
   u"Jayme Lynn Blaschke",
   u"James Blaylock",
   u"James Blish",
   u"Robert Bloch",
   u"Alexander Bogdanov",
   u"Maya Kaathryn Bohnhoff",
   u"Nelson S. Bond",
   u"Pierre Bordage",
   u"Anthony Boucher",
   u"Pierre Boulle",
   u"Sydney J. Bounds",
   u"Ben Bova",
   u"Leigh Brackett",
   u"Ray Bradbury",
   u"Marion Zimmer Bradley",
   u"Gillian Bradshaw",
   u"Paolo Brera",
   u"Reginald Bretnor",
   u"David Brin",
   u"Damien Broderick",
   u"Kristi Brooks",
   u"Terry Brooks",
   u"John Brosnan",
   u"Eric Brown",
   u"Fredric Brown",
   u"Rosel George Brown",
   u"Simon Brown",
   u"John Brunner",
   u"Steven Brust",
   u"Edward Bryant",
   u"Valery Bryusov",
   u"Tobias S. Buckell",
   u"Algis Budrys",
   u"Vitaly Bugrov",
   u"Lois McMaster Bujold",
   u"Mikhail Bulgakov",
   u"Faddey Bulgarin",
   u"Kenneth Bulmer",
   u"Kir Bulychev",
   u"Chris Bunch",
   u"David R. Bunch",
   u"Anthony Burgess",
   u"Yuli Burkin",
   u"Edgar Rice Burroughs",
   u"Michael A. Burstein",
   u"F. M. Busby",
   u"Aleksandr Bushkov",
   u"Jim Butcher",
   u"Octavia E. Butler",
   u"Pat Cadigan",
   u"Jack Cady",
   u"Martin Caidin",
   u"John W. Campbell, Jr.",
   u"Karel Čapek",
   u"Orson Scott Card",
   u"Terry Carr",
   u"Lin Carter",
   u"Cleve Cartmill",
   u"Jeffrey Carver",
   u"Gianluca Casseri",
   u"Jay Caselberg",
   u"Jack L. Chalker",
   u"A. Bertram Chandler",
   u"Suzy McKee Charnas",
   u"Daína Chaviano",
   u"Richard Chwedyk",
   u"C. J. Cherryh",
   u"Ted Chiang",
   u"Charles Chilton",
   u"John Christopher",
   u"Massimo Citi",
   u"Charles Heber Clark",
   u"Arthur C. Clarke",
   u"Jo Clayton",
   u"Hal Clement",
   u"John Cleve",
   u"Mark Clifton",
   u"Brenda Clough",
   u"John Clute",
   u"Stephen Euin Cobb",
   u"Stanton A. Coblentz",
   u"Theodore Cogswell",
   u"Frona Eunice Wait Colburn",
   u"Erroll Collins",
   u"Suzanne Collins",
   u"David G. Compton",
   u"Michael Coney",
   u"Groff Conklin",
   u"Storm Constantine",
   u"Glen Cook",
   u"Hugh Cook",
   u"Paul Cook",
   u"Edmund Cooper",
   u"Alfred Coppel",
   u"Richard Cowper",
   u"Erle Cox",
   u"John G. Cramer",
   u"Michael Crichton",
   u"Compton N. Crook",
   u"John Crowley",
   u"Andrew Crumey",
   u"Ray Cummings",
   u"Julie E. Czerneda",
   u"Roald Dahl",
   u"Brian Daley",
   u"John Dalmas",
   u"Tony Daniel",
   u"Jack Dann",
   u"Maurice Georges Dantec",
   u"Dennis Danvers",
   u"Clark Darlton",
   u"Avram Davidson",
   u"Chan Davis",
   u"L. Sprague de Camp",
   u"Antonio de Macedo",
   u"James De Mille",
   u"Marianne de Pierres",
   u"Stephen Dedman",
   u"Lester del Rey",
   u"Samuel R. Delany",
   u"Bradley Denton",
   u"August Derleth",
   u"A.J. Deutsch",
   u"Graham Diamond",
   u"Philip K. Dick",
   u"Gordon R. Dickson",
   u"William C. Dietz",
   u"Thomas M. Disch",
   u"Alfred Döblin",
   u"Cory Doctorow",
   u"Stephen Donaldson",
   u"Candas Dorsey",
   u"Arthur Conan Doyle",
   u"Debra Doyle",
   u"Gardner Dozois",
   u"David Drake",
   u"Tananarive Due",
   u"Jacek Dukaj",
   u"Jean-Claude Dunyach",
   u"G. C. Edmondson",
   u"George Alec Effinger",
   u"Ivan Antonovich Efremov",
   u"Greg Egan",
   u"Suzette Haden Elgin",
   u"William B. Ellern",
   u"Harlan Ellison",
   u"Roger Elwood",
   u"Carol Emshwiller",
   u"M. J. Engh",
   u"Walter Ernsting",
   u"Andreas Eschbach",
   u"Kelley Eskridge",
   u"Valerio Evangelisti",
   u"Christopher Evans",
   u"Jane Fancher",
   u"Philip José Farmer",
   u"Nabil Farouk",
   u"Howard Fast",
   u"John Russell Fearn",
   u"Cynthia Felice",
   u"Brad Ferguson",
   u"Sheila Finch",
   u"Jack Finney",
   u"Nicholas Fisk",
   u"Camille Flammarion",
   u"Eric Flint",
   u"Michael Flynn",
   u"Charles L. Fontenay",
   u"Jeffrey Ford",
   u"John M. Ford",
   u"William R. Forstchen",
   u"Edward Morgan Forster",
   u"Robert L. Forward",
   u"Richard Foss",
   u"Alan Dean Foster",
   u"M. A. Foster",
   u"Karen Joy Fowler",
   u"Randall Frakes",
   u"Herbert W. Franke",
   u"Yves Fremion",
   u"C. S. Friedman",
   u"Oscar J. Friend",
   u"Esther Friesner",
   u"Neil Gaiman",
   u"Raymond Z. Gallun",
   u"Daniel F. Galouye",
   u"James Alan Gardner",
   u"Martin Gardner",
   u"Richard Garfinkle",
   u"Randall Garrett",
   u"Mary Gentle",
   u"Alistair Gentry",
   u"Peter George",
   u"Hugo Gernsback",
   u"David Gerrold",
   u"Mark S. Geston",
   u"Edward Gibson",
   u"Gary Gibson",
   u"William Gibson",
   u"Alexis A. Gilliland",
   u"Molly Gloss",
   u"Tom Godwin",
   u"H. L. Gold",
   u"Lee Gold",
   u"Lisa Goldstein",
   u"Kathleen Ann Goonan",
   u"Richard Gordon",
   u"Phyllis Gotlieb",
   u"Ron Goulart",
   u"Charles L. Grant",
   u"Roland J. Green",
   u"Colin Greenland",
   u"William Greenleaf",
   u"Lois Gresh",
   u"George Griffith",
   u"Nicola Griffith",
   u"Jon Courtenay Grimwood",
   u"Ken Grimwood",
   u"Alexander Gromov",
   u"Martin Grzimek",
   u"Wyman Guin",
   u"Eileen Gunn",
   u"James E. Gunn",
   u"PJ Haarsma",
   u"Karen Haber",
   u"H. Rider Haggard",
   u"Ronald M. Hahn",
   u"Jack C. Haldeman II",
   u"Joe Haldeman",
   u"Barbara Hambly",
   u"Edmond Hamilton",
   u"Peter F. Hamilton",
   u"Elizabeth Hand",
   u"Lee Harding",
   u"Charles L. Harness",
   u"Tara K. Harper",
   u"Clare Winger Harris",
   u"Harry Harrison",
   u"M. John Harrison",
   u"Henry Hasse",
   u"Simon Hawke",
   u"Peter Heck",
   u"Robert A. Heinlein",
   u"Zenna Henderson",
   u"Brian Herbert",
   u"Frank Herbert",
   u"Philip E. High",
   u"Douglas Hill",
   u"Ernest Hill",
   u"Christopher Hinz",
   u"Morioka Hiroyuki",
   u"P. C. Hodgell",
   u"William Hope Hodgson",
   u"E. T. A. Hoffman",
   u"Lee Hoffman",
   u"H. H. Hollis",
   u"James P. Hogan",
   u"Elizabeth Holden",
   u"Robert Holdstock",
   u"Nalo Hopkinson",
   u"Shinichi Hoshi",
   u"Fred Hoyle",
   u"L. Ron Hubbard",
   u"Marek Huberath",
   u"Matt Hughes",
   u"Monica Hughes",
   u"Cyril Hume",
   u"Stephen Hunt",
   u"Aldous Huxley",
   u"Ibn al-Nafis",
   u"Dean Ing",
   u"Muhammed Zafar Iqbal",
   u"Simon Ings",
   u"John Jakes",
   u"Phil Janes",
   u"Laurence Janifer",
   u"Wolfgang Jeschke",
   u"K. W. Jeter",
   u"Michel Jeury",
   u"George Clayton Johnson",
   u"D. F. Jones",
   u"Gwyneth Jones",
   u"Neil R. Jones",
   u"Raymond F. Jones",
   u"Diana Wynne Jones",
   u"Robert Jordan",
   u"M. K. Joseph",
   u"JS Joubert",
   u"Theodore Judson",
   u"Franz Kafka",
   u"Janet Kagan",
   u"Michael Kandel",
   u"Colin Kapp",
   u"Alexander Kazantsev",
   u"Joseph E. Kelleam",
   u"James Patrick Kelly",
   u"Katharine Kerr",
   u"John Kessel",
   u"Roy Kettle",
   u"Alexander Key",
   u"Daniel Keyes",
   u"Gregory Keyes",
   u"David Kier",
   u"Caitlín R. Kiernan",
   u"Lee Killough",
   u"Wade A. Kimberlin",
   u"Sara King",
   u"Stephen King",
   u"T. Jackson King",
   u"Vincent King",
   u"John Kippax",
   u"Annette Curtis Klause",
   u"Donald Kingsbury",
   u"Hugh Kingsmill",
   u"David Barr Kirtley",
   u"Gérard Klein",
   u"Nigel Kneale",
   u"Damon Knight",
   u"Dean R. Koontz",
   u"Cyril M. Kornbluth",
   u"Tom Kratman",
   u"Nancy Kress",
   u"Günther Krupkat",
   u"Zoran Krušvar",
   u"Michael P. Kube-McDowell",
   u"Henry Kuttner",
   u"R. A. Lafferty",
   u"Geoffrey Landis",
   u"David Langford",
   u"Sterling E. Lanier",
   u"Justine Larbalestier",
   u"Glen A. Larson",
   u"Kurd Lasswitz",
   u"Keith Laumer",
   u"Stephen R. Lawhead",
   u"Ursula K. Le Guin",
   u"Gentry Lee",
   u"Sharon Lee",
   u"Stan Lee",
   u"Tanith Lee",
   u"Kimmo Lehtonen",
   u"Fritz Leiber",
   u"Murray Leinster",
   u"Stanisław Lem",
   u"Edward M. Lerner",
   u"Doris Lessing",
   u"Jonathan Lethem",
   u"Paul Levinson",
   u"Roger Levy",
   u"C. S. Lewis",
   u"Shariann Lewitt",
   u"Jacqueline Lichtenberg",
   u"Brad Linaweaver",
   u"Dénis Lindbohm",
   u"Liu Cixin",
   u"John Uri Lloyd",
   u"Jack London",
   u"Barry B. Longyear",
   u"Jean Lorrah",
   u"H. P. Lovecraft",
   u"Archibald Low",
   u"Lois Lowry",
   u"George Lucas",
   u"Lucian",
   u"Nicole Luiken",
   u"Sergey Lukyanenko",
   u"Sam Lundwall",
   u"Duncan Lunan",
   u"Richard A. Lupoff",
   u"Darko Macan",
   u"James D. Macdonald",
   u"John D. MacDonald",
   u"F. Gwynplaine MacIntyre",
   u"R. W. Mackelworth",
   u"Katherine MacLean",
   u"Ian R. MacLeod",
   u"Ken MacLeod",
   u"Angus MacVicar",
   u"Tom Maddox",
   u"Charles Eric Maine",
   u"Donald Malcolm",
   u"Barry N. Malzberg",
   u"Laurence Manning",
   u"Leo Margulies",
   u"Stephen Marley",
   u"Paul Marlowe",
   u"George R. R. Martin",
   u"David Marusek",
   u"Richard Matheson",
   u"Julian May",
   u"Paul J. McAuley",
   u"Anne McCaffrey",
   u"Wil McCarthy",
   u"David McDaniel",
   u"Jack McDevitt",
   u"Ian McDonald",
   u"Maureen F. McHugh",
   u"J. T. McIntosh",
   u"Vonda McIntyre",
   u"Neil McMahon",
   u"Sean McMullen",
   u"Mike McQuay",
   u"John Meaney",
   u"Capt. S.P. Meek",
   u"Richard C. Meredith",
   u"Robert Merle",
   u"Judith Merril",
   u"A. Merritt",
   u"Robert A. Metzger",
   u"Gustav Meyrink",
   u"China Miéville",
   u"P. Schuyler Miller",
   u"Steve Miller",
   u"Walter M. Miller, Jr.",
   u"Edward Page Mitchell",
   u"Kirk Mitchell",
   u"Syne Mitchell",
   u"Naomi Mitchison",
   u"Premendra Mitra",
   u"L. E. Modesitt, Jr.",
   u"Donald Moffitt",
   u"Elizabeth Moon",
   u"Michael Moorcock",
   u"Alan Moore",
   u"C. L. Moore",
   u"Patrick Moore",
   u"Ward Moore",
   u"Daniel Keys Moran",
   u"Dan Morgan",
   u"Richard Morgan",
   u"Chris Moriarty",
   u"Chris Morris",
   u"Janet Morris",
   u"William Morrison",
   u"James Morrow",
   u"Sam Moskowitz",
   u"Pat Murphy",
   u"Linda Nagata",
   u"Jayant Narlikar",
   u"Ondřej Neff",
   u"Geoff Nelder",
   u"Radell F. Nelson",
   u"István Nemere",
   u"Josef Nesvadba",
   u"Kris Neville",
   u"Yuri Nikitin",
   u"Larry Niven",
   u"Nick Nielsen",
   u"William F. Nolan",
   u"Jeff Noon",
   u"John Norman",
   u"Lisanne Norman",
   u"Eric North",
   u"Andre Norton",
   u"Alan E. Nourse",
   u"Eric S. Nylund",
   u"Robert C. O'Brien",
   u"Kevin O'Donnell, Jr.",
   u"Patrick O'Leary",
   u"Vladimir Obruchev",
   u"Andrew J. Offutt",
   u"Nnedi Okorafor",
   u"Chad Oliver",
   u"Jerry Oltion",
   u"John Ostrander",
   u"Jerry Ordway",
   u"Marek Oramus",
   u"Rebecca Ore",
   u"George Orwell",
   u"George Pal",
   u"David R. Palmer",
   u"Ray Palmer",
   u"Edgar Pangborn",
   u"Alexei Panshin",
   u"Cory Panshin",
   u"James B.Patterson",
   u"Stel Pavlou",
   u"Donald G. Payne",
   u"Hayford Peirce",
   u"Charles Pellegrino",
   u"Lawrence Person",
   u"Steve Perry",
   u"Emil Petaja",
   u"John T. Phillifent",
   u"Mark Phillips",
   u"Rog Phillips",
   u"Eden Phillpotts",
   u"John R. Pierce",
   u"Marge Piercy",
   u"H. Beam Piper",
   u"Doris Piserchia",
   u"Brian Plante",
   u"Charles Platt",
   u"P. J. Plauger",
   u"Van Allen Plexico",
   u"Edgar Allan Poe",
   u"Frederik Pohl",
   u"Arthur Porges",
   u"Jerry Pournelle",
   u"Terry Pratchett",
   u"Robert Presslie",
   u"Paul Preuss",
   u"Christopher Priest",
   u"Philip Pullman",
   u"Roberto Quaglia",
   u"W. T. Quick",
   u"Daniel Quinn",
   u"Ayn Rand",
   u"Bill Ransom",
   u"Satyajit Ray",
   u"Tom Reamy",
   u"Melanie Rawn",
   u"Robert Reed",
   u"Miha Remec",
   u"Laura Resnick",
   u"Mike Resnick",
   u"Alastair Reynolds",
   u"Mack Reynolds",
   u"Christopher Rice",
   u"John Ringo",
   u"Adam Roberts",
   u"Keith Roberts",
   u"Shauna S. Roberts",
   u"Sujatha Rangarajan",
   u"Frank M. Robinson",
   u"Jeanne Robinson",
   u"Kim Stanley Robinson",
   u"Spider Robinson",
   u"Justina Robson",
   u"Esther Rochon",
   u"Ross Rocklynne",
   u"Gene Roddenberry",
   u"Carlos Rasch",
   u"Simon Rose",
   u"Joel Rosenberg",
   u"J.-H. Rosny",
   u"Milton A. Rothman",
   u"Tony Rothman",
   u"William Rotsler",
   u"Christopher Rowley",
   u"Rudy Rucker",
   u"Kristine Kathryn Rusch",
   u"Joanna Russ",
   u"Richard Paul Russo",
   u"Eric Frank Russell",
   u"Mary Doria Russell",
   u"Geoff Ryman",
   u"Fred Saberhagen",
   u"Carl Sagan",
   u"Nick Sagan",
   u"Don Sakers",
   u"Margaret St. Clair",
   u"Emilio Salgari",
   u"Domingo Santos",
   u"Pamela Sargent",
   u"Al Sarrantonio",
   u"Robert J. Sawyer",
   u"John Scalzi",
   u"Nat Schachner",
   u"Paul Scheerbart",
   u"James H. Schmitz",
   u"Stanley Schmidt",
   u"Karl Schroeder",
   u"J. Neil Schulman",
   u"George H. Scithers",
   u"Thomas N. Scortia",
   u"Arthur Sellings",
   u"Józef Sękowski",
   u"Rod Serling",
   u"Michael Shaara",
   u"Eric Shapiro",
   u"William Shatner",
   u"Richard S. Shaver",
   u"Bob Shaw",
   u"Nisi Shawl",
   u"Robert Sheckley",
   u"Charles Sheffield",
   u"Mary Shelley",
   u"Lucius Shepard",
   u"Joel Shepherd",
   u"M. P. Shiel",
   u"T. L. Sherred",
   u"Lewis Shiner",
   u"Sharon Shinn",
   u"Wilmar H. Shiras",
   u"John Shirley",
   u"Pavel Shumil",
   u"William Shunn",
   u"Luís Filipe Silva",
   u"Robert Silverberg",
   u"Clifford D. Simak",
   u"Dan Simmons",
   u"Johanna Sinisalo",
   u"Curt Siodmak",
   u"John Sladek",
   u"William Sleator",
   u"Joan Slonczewski",
   u"Clark Ashton Smith",
   u"Cordwainer Smith",
   u"E. E. Smith",
   u"Michael Marshall Smith",
   u"George O. Smith",
   u"L. Neil Smith",
   u"Melinda Snodgrass",
   u"Jerry Sohl",
   u"Martha Soukup",
   u"Steven Spielberg",
   u"Norman Spinrad",
   u"Nancy Springer",
   u"Margaret St. Clair",
   u"Dana Stabenow",
   u"Brian Stableford",
   u"Michael A. Stackpole",
   u"Olaf Stapledon",
   u"Roman Frederick Starzl",
   u"Christopher Stasheff",
   u"John Steakley",
   u"Allen Steele",
   u"Angela Steinmüller",
   u"Karlheinz Steinmüller",
   u"Neal Stephenson",
   u"Jacques Sternberg",
   u"Bruce Sterling",
   u"Francis Stevens",
   u"Marc Stiegler",
   u"Ron Stillman",
   u"G. Harry Stine",
   u"S. M. Stirling",
   u"John E. Stith",
   u"J. Michael Straczynski",
   u"Giampietro Stocco",
   u"Charles Stross",
   u"Arkady and Boris Strugatsky",
   u"Theodore Sturgeon",
   u"Somtow Sucharitkul",
   u"Richard J. Sutcliffe",
   u"Michael Swanwick",
   u"Jonathan Swift",
   u"Michael Szameit",
   u"John Taine",
   u"Stephen Tall",
   u"Yoshiki Tanaka",
   u"Charles R. Tanner",
   u"Howard Tayler",
   u"Mark Anthony Taylor",
   u"Dr. Travis S. Taylor",
   u"Steve Rasnic Tem",
   u"William F. Temple",
   u"Tais Teng",
   u"William Tenn",
   u"Sheri S. Tepper",
   u"Tom Terry",
   u"Walter Tevis",
   u"Robert Thurston",
   u"Mark W. Tiedemann",
   u"Patrick Tilley",
   u"James M. Tiptree, Jr",
   u"Aleksei Nikolaevich Tolstoi",
   u"Karen Traviss",
   u"E. C. Tubb",
   u"George Tucker",
   u"Wilson Tucker",
   u"George Turner",
   u"Harry Turtledove",
   u"Mary Turzillo",
   u"John Twelve Hawks",
   u"Kathy Tyers",
   u"Steven Utley",
   u"Jack Vance",
   u"Jeff VanderMeer",
   u"James Van Pelt",
   u"Sydney J. Van Scyoc",
   u"Robert E. Vardeman",
   u"A. E. van Vogt",
   u"John Varley",
   u"Vladimir Vasilyev",
   u"Vercors",
   u"Jean Bruller",
   u"Jules Verne",
   u"Joan D. Vinge",
   u"Vernor Vinge",
   u"Voltaire",
   u"Elisabeth Vonarburg",
   u"Kurt Vonnegut, Jr.",
   u"Roland C. Wagner",
   u"Howard Waldrop",
   u"F. L. Wallace",
   u"Ian Wallace",
   u"Hugh Walters",
   u"Donald Wandrei",
   u"Ian Watson",
   u"Lawrence Watt-Evans",
   u"Peter Watts",
   u"Don Webb",
   u"David Weber",
   u"Stanley G. Weinbaum",
   u"Jan Weiss",
   u"Angus Wells",
   u"H. G. Wells",
   u"Martha Wells",
   u"K. D. Wentworth",
   u"Wallace West",
   u"Scott Westerfeld",
   u"Suzanne Weyn",
   u"James White",
   u"Steve White",
   u"Ted White",
   u"Sonny Whitelaw",
   u"Cherry Wilder",
   u"Kate Wilhelm",
   u"Lynda Williams",
   u"Liz Williams",
   u"Rob Williams",
   u"Tad Williams",
   u"Walter Jon Williams",
   u"Jack Williamson",
   u"Michael Z. Williamson",
   u"Connie Willis",
   u"Colin Wilson",
   u"D. Harlan Wilson",
   u"F. Paul Wilson",
   u"Robert Anton Wilson",
   u"Robert Charles Wilson",
   u"Richard Wilson",
   u"David Wingrove",
   u"Adam Wiśniewski-Snerg",
   u"Otto Witt",
   u"Gene Wolfe",
   u"Donald A. Wollheim",
   u"Edmund Wnuk-Lipinski",
   u"Jack Womack",
   u"John C. Wright",
   u"S. Fowler Wright",
   u"Stefan Wul",
   u"John Wyndham",
   u"Tetsu Yano",
   u"Jane Yolen",
   u"Robert Franklin Young",
   u"Charles Yu",
   u"Timothy Zahn",
   u"Janusz A. Zajdel",
   u"Yevgeny Zamyatin",
   u"George Zebrowski",
   u"Roger Zelazny",
   u"Tully Zetford",
   u"Sarah Zettel",
   u"Rafal A. Ziemkiewicz",
   u"Andrzej Ziemiański",
   u"Aleksandar Ziljak",
   u"Werner Zillig",
   u"David Zindell",
   u"Pamela Zoline",
    ]